name: intern-bot
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml
      - env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          SMS_TO_LIST: ${{ secrets.SMS_TO_LIST }}
        run: python intern-bot/watcher.py   # ← path fix
      - name: Persist seen.json
        run: |
          git config user.name "intern-bot"
          git config user.email "intern-bot@users.noreply.github.com"
          git add intern-bot/seen.json || true   # ← path fix
          git commit -m "update seen.json" || true
          git push || true
